version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    networks:
      - keploy-network
    volumes:
      - ./:/app
      - /app/node_modules

networks:
  keploy-network:
    name: keploy-network